### ISSUE TITLE
Test failed on Windows

### ISSUE THREAD

**Issue by bdecarne** [seglo/connect-prism#22]
When i try to run the tests, i got :

```
  2 failing

  1) prism task initialization clear mocks on start "before each" hook:
     Error: EPERM, operation not permitted 'D:\connect-prism\mocks\clearOnStartTest\foo.json'
      at Object.fs.openSync (fs.js:427:18)
      at Context.<anonymous> (D:\connect-prism\test\integration\prism-init-spec.js:78:12)
      at callFn (D:\connect-prism\node_modules\grunt-mocha-test\node_modules\mocha\lib\runnable.js:223:21)
      at Hook.Runnable.run (D:\connect-prism\node_modules\grunt-mocha-test\node_modules\mocha\lib\runnable.js:216:7)
      at next (D:\connect-prism\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:258:10)
      at Object._onImmediate (D:\connect-prism\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)

  2) mock filename generator should support a human readable filename generator function with truncation:
     TypeError: Cannot read property 'length' of undefined
      at Context.<anonymous> (D:\connect-prism\test\unit\mock-filename-generator-spec.js:65:48)
      at callFn (D:\connect-prism\node_modules\grunt-mocha-test\node_modules\mocha\lib\runnable.js:223:21)
      at Test.Runnable.run (D:\connect-prism\node_modules\grunt-mocha-test\node_modules\mocha\lib\runnable.js:216:7)
      at Runner.runTest (D:\connect-prism\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:373:10)
      at D:\connect-prism\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:451:12
      at next (D:\connect-prism\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:298:14)
      at D:\connect-prism\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:308:7
      at next (D:\connect-prism\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:246:23)
      at Object._onImmediate (D:\connect-prism\node_modules\grunt-mocha-test\node_modules\mocha\lib\runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)


npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

Related to https://github.com/joyent/node/issues/6599 ?

**Comment by seglo** [comment]
Yes, all these errors were related to windows filesystem in some way.  Thanks raising the issue.

https://github.com/seglo/connect-prism/commit/7ae23c7786967f0b515a20b8b80b6c212f1101e1
