### ISSUE TITLE
Collision with compiled Traceur runtime in Node Enviroment 

### ISSUE THREAD

**Issue by dman777** [seglo/connect-prism#25]
Please reference: https://github.com/sindresorhus/gulp-traceur/issues/46#issuecomment-62760878

I am using `var prism = require('connect-prism');` in a task name connect.js. In a separate task, if I ` var traceur = require('gulp-traceur');` it causes the compiled traceur in gulp-traceur to complain about the traceur runtime environment. But if I remove `var prism = require('connect-prism');`, I do not have this issue. 

This goes the same with inside the node shell:
with `var prism = require('connect-prism');`
```javascript
> var prism = require('connect-prism');
undefined
>  var traceur = require('gulp-traceur');
TypeError: undefined is not a function
    at eval (eval at <anonymous> (/home/one/github/encore-ui-template/node_modules/gulp-traceur/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:498:17)
    at eval (eval at <anonymous> (/home/one/github/encore-ui-template/node_modules/gulp-traceur/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:601:3)
    at eval (native)
    at Object.<anonymous> (/home/one/github/encore-ui-template/node_modules/gulp-traceur/node_modules/traceur/src/node/traceur.js:24:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
> 
```
----------------------------------------------------
without `var prism = require('connect-prism');`
```javascript 
>  var traceur = require('gulp-traceur');
undefined
> 
```

**Comment by seglo** [comment]
I'm not able to reproduce this issue.  I recently released `1.0.1` of `connect-prism`, maybe you should see if you still get this issue with that version.

```bash
> var prism = require('connect-prism')
undefined
> var traceur = require('gulp-traceur')
undefined
> 
(^C again to quit)
> 
seglo@bit:~/source/prism-sample-project$ npm list gulp-traceur
prism-sample-project@0.0.7 /home/seglo/source/prism-sample-project
└── gulp-traceur@0.15.0 

seglo@bit:~/source/prism-sample-project$ npm list connect-prism
prism-sample-project@0.0.7 /home/seglo/source/prism-sample-project
└── connect-prism@1.0.1 

```
